Repository EkitaiKani/Week2TeamRepo, pull requests merged in 2024-10, with the labels that each got.

#11 feat: added file called ridzal.txt
  ridzal.txt
Labels: enhancement

#12 pull readme.md
  ridzal.txt
Labels: documentation

#13 sup -wh
  ridzal.txt
Labels: documentation, question

#14 Jwbranch
  README.md
Labels: enhancement
